# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-06 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('init_user_password', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('user_number', models.IntegerField(default=0)),
                ('real_database', models.CharField(blank=True, max_length=15)),
                ('template_database', models.CharField(blank=True, max_length=15)),
                ('subdomain', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('domain', models.CharField(blank=True, max_length=15)),
                ('admin_password', models.CharField(blank=True, max_length=15)),
                ('main_server', models.BooleanField(default=False)),
                ('available_package_ids', models.ManyToManyField(to='webcam.Packages')),
            ],
        ),
        migrations.AddField(
            model_name='modules',
            name='package_ids',
            field=models.ManyToManyField(to='webcam.Packages'),
        ),
        migrations.AddField(
            model_name='instances',
            name='package_ids',
            field=models.ManyToManyField(to='webcam.Packages'),
        ),
        migrations.AddField(
            model_name='instances',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcam.Servers'),
        ),
        migrations.AddField(
            model_name='instances',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcam.ResUsers'),
        ),
    ]
